services:
  gorilla:
    image: gorilla:latest
    env_file:
      - .env.gorilla
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:latest
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"