apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: gorilla
  labels:
    app: worker
    app.kubernetes.io/name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        app.kubernetes.io/name: worker
    spec:
      containers:
      - name: worker
        image: gorilla:latest
        imagePullPolicy: IfNotPresent
        args: 
        - worker
        envFrom:
        - configMapRef:
            name: config-gorilla